version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_local_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: blooddonordb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  staging-db:
    image: mysql:8.0
    container_name: mysql_staging
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: blooddonordb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - staging_mysql_data:/var/lib/mysql

  vault:
    container_name: "blooddonar_vault"
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
    ports:
      - "8200:8200"

  keycloak:
    container_name: keycloak_blood_donor_app
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - 8090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak:/tmp/keycloak

  redis:
    image: redis:7.4.2
    ports:
      - 6379:6379




volumes:
  mysql_data: {}
  staging_mysql_data: {}


